universe:
  min_price: 2.0
  min_adv_usd: 20000000   # $20M
  min_avg_vol: 1000000
  min_atr_pct: 0.03       # 3%

signal:
  breakout_threshold: 0.003    # 1.2% above prev high/low
  vol_multiplier: 1.0          # 150% of avg volume
  allow_shorts: false

execution:
  entry_limit_pct: 0.005       # use LMT within 0.5%
  stop_loss_pct: 0.03
  trail_start_pct: 0.05
  trail_pct: 0.04
